module.exports = {
  'extends': [
    'airbnb',
    'plugin:jest/recommended',
    'prettier',
  ],
  'rules': {
    'no-underscore-dangle': [0],
    'consistent-return': 0,
    'no-unused-expressions': [2, { 'allowShortCircuit': true }],
    'no-param-reassign': 0,
    'no-shadow': 0,
    'func-names': 0,
    'guard-for-in': 0,
    'no-restricted-syntax': [2, 'WithStatement'],
    'no-unused-vars': [2, { 'vars': 'all', 'args': 'none' }],
    'no-console': 0,
    'radix': 0,
    'react/jsx-closing-bracket-location': 0,
    'react/jsx-curly-spacing': 0,
    'react/jsx-equals-spacing': 0,
    'react/jsx-first-prop-new-line': 0,
    'react/jsx-indent': 0,
    'react/jsx-indent-props': 0,
    'react/jsx-space-before-closing': 0,
  },
}